@api = http://localhost:3000/api/tasks

### get tasks
{{api}}

### create task
POST {{api}}
Content-Type: application/json

{
  "title": "second task 2",
  "description": "second desc"
}

### some validation
POST {{api}}

### get single task
GET {{api}}/6160b6d25aca70fd0ce7f823

### Update a single task
PUT {{api}}/6160b6d25aca70fd0ce7f823
Content-Type: application/json

{
  "title": "I have to create a next app"
}

### delete a single task
DELETE {{api}}/6160bb92b2a5d3c03dc77223